[package]
name = "aoc-ornaments"
version = "0.1.7"
edition = "2024"
rust-version = "1.85"

[features]
default = ["miette"]

[dependencies]
glam = "0.29"
thiserror = "2.0"
miette = { version = "7.4", optional = true }
nom = "7.0"

[dev-dependencies]
md5 = "0.7"
rstest = "0.23.0"