[package]
name = "aoc-ornaments"
version = "0.1.7"
edition = "2024"
rust-version = "1.85"

[features]
default = ["miette"]

[dependencies]
glam = "0.29"
itertools = "0.14"
thiserror = "2.0"
miette = { version = "7.4", optional = true, features = ["fancy"]}
nom = "7.0"

[dev-dependencies]
md5 = "0.7"
rstest = "0.24"
serde_json = "1.0"