[package]
name = "aoc-ornaments"
version = "0.1.3"
edition = "2024"
rust-version = "1.85"

[features]
default = ["miette"]

[dependencies]
miette = { version = "7.4.0", optional = true}

[dev-dependencies]
rstest = "0.23.0"